FROM rust:1.48-slim AS build
RUN cargo install ripgrep



# Install and get rg as follows
# $ docker build -t rg-builder:0.1 .
# $ docker run -it -d --rm --name rg-builder rg-builder:0.1 
# $ docker cp rg-builder:/usr/local/cargo/bin/rg .
# $ docker stop rg-builder

